# 対象のURLリスト

targets:
  azure_updates:
    url: 'https://azure.microsoft.com/ja-jp/updates/'
    parser: 'AzureUpdatesParser'
#  追加のターゲットがある場合は以下のように定義
#  another_target:
#    url: 'https://example.com/updates'
#    parser: 'AnotherSiteParser'
